block_detection_tracking_node:
  ros__parameters:

    detection:
      # -------------------------
      # Detection filtering
      # -------------------------
      min_confidence: 0.5
      min_bbox_area: 600.0
      # -------------------------
      # Tracking & association
      # -------------------------
      iou_threshold: 0.35
      containment_ratio: 0.85
      suppression_radius: 0.6
      confirm_age: 3
      max_misses: 7
        # -------------------------
      # Debugging
      # -------------------------
      publish_debug_image: true
      bypass_tracking: true

