block_world_model_node:
  ros__parameters:

    world_model:
      world_frame: world
      min_points: 30

    tracker:
      min_hits: 3
      max_misses: 10
      chi2_gate: 7.815   # 95% for 3D

      velocity_damping: 0.9

      process_noise:
        px: 1.0e-4
        py: 1.0e-4
        pz: 1.0e-4
        yaw: 1.0e-4
        vx: 5.0e-2
        vy: 5.0e-2
        vz: 5.0e-2

      measurement_noise:
        px: 0.05
        py: 0.05
        pz: 0.07
        yaw: 0.15

    icp:
      enable: false
      min_hits: 5
      max_covariance: 0.02
      service_name: /block_registration/refine
